select exam_type,
(case exam_type
when 'MCE' then 'OBJECTIVE'
WHEN 'TF'then 'OBJECTIVE'
when 'FIB'then 'OBJECTIVE'
when 'ESS' then 'SUBJECTIVE'
when'SA'then 'SUBJECTIVE'
when 'PS' then 'ANALYTICAL'
when 'LAB' THEN 'PRACTICAL'
ELSE 'NOT PERMITTED' END) AS NATURE_OF_EXAM
from ad_exam_type;


SELECT*
FROM AD_EXAM_RESULTS;


SELECT STUDENT_ID,
MARKS,
(CASE WHEN MARKS<60 THEN 'FAIL'
WHEN MARKS>60 AND MARKS<70 THEN 'SATISFACOTOR'
WHEN MARKS >70 AND MARKS<80 THEN 'GOOD'
WHEN MARKS>80 AND MARKS<90 THEN 'VERY GOOD'
WHEN MARKS>90 THEN 'EXCELLENT' ELSE 'SATISFACOTOR'
END) AS GRADE_REMARK
FROM AD_EXAM_RESULTS;



select exam_type,
DECODE (exam_type,
'MCE' , 'OBJECTIVE',
'TF', 'OBJECTIVE',
'FIB','OBJECTIVE',
'ESS' , 'SUBJECTIVE',
'SA','SUBJECTIVE',
'PS' , 'ANALYTICAL',
 'LAB' , 'PRACTICAL',
'NOT PERMITTED') AS NATURE_OF_EXAM
from ad_exam_type;



ACRIVITY_GUDE_AG:
